### ISSUE TITLE
How to raise an issue

### ISSUE THREAD

**Issue by BenAAndrew** [BenAAndrew/Voice-Cloning-App#1]
### Use a clear heading (include in brackets which stage this relates to: installation, dataset, training or synthesis)

If raising a bug: 
- Add the **bug** label
- `Paste the error log`
- Describe what you were trying to do when the issue occurred 

If asking for help:
- Add the **help wanted** label
- Describe how far you've got in the process
- **Please do not ask others to create a voice for you. These issues will be removed**

If suggesting an enhancement:
- Add the **enhancement** label
- Describe the improvement and why it may help

**Comment by D4RKH0R1Z0N** [comment]
How much time does it take to train the voice cloning project?

**Comment by TheLustriVA** [comment]
**Summary**
I get the same UnicodeDecodeError under different circumstances when annotating a new dataset.

**Platform**
App version: 1.1.1
OS: Windows 10.0.19044 Build 19044 (64-bit)
Browser: Firefox 101.0.1 (64-bit)
Address: localhost:5000

**Error message**
```
Type: UnicodeDecodeError
Text: 'utf-8' codec can't decode byte 0x92 in position 8128: invalid start byte
Full: Traceback (most recent call last): File "flask\app.py", line 1950, in full_dispatch_request File "flask\app.py", line 1936, in dispatch_request File "application\views.py", line 458, in label_clip File "dataset\analysis.py", line 134, in update_dataset_info File "dataset\analysis.py", line 29, in get_text File "codecs.py", line 321, in decode UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 8128: invalid start byte 
```


**Dataset details**
Audio: PCM 16-bit WAV @ 22050hz
Text: .txt file stripped of non-ASCII unicode characters.

**Issue**
After creating the dataset in Voice Cloning App, I went to 'Manage Datasets' and selected the new dataset from the drop-down.I successfully annotated one clip, but encountered the above error message when I hit "Submit Query" for the second clip. Subsequent annotations of different clips using both direct typing, pasting from a text cleaner, and pasting from the original in Notepad++ resulted in the same error. I am unable to annotate the dataset further.

**Expected behavior**
Hitting "Submit Query" would take me to the next clip needing annotation.

**Steps taken**

- Attempted multiple forms of input
- Attempted annotating different clips
- Deleted all local browser data for localhost
- Used a new tab
- Restarted the app
