### ISSUE TITLE
JSONDecodeError During Synthesis

### ISSUE THREAD

**Issue by daynightcycle** [BenAAndrew/Voice-Cloning-App#100]
**Type:** JSONDecodeError
**Text:** Expecting value: line 1 column 1 (char 0)
**Full:** Traceback (most recent call last): File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request rv = self.dispatch_request() File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args) File "/home/sugar/BenAAndrew/Voice-Cloning-App/application/views.py", line 302, in synthesis_setup_post vocoder = Hifigan(model_path, model_config_path) File "/home/sugar/BenAAndrew/Voice-Cloning-App/synthesis/vocoders/hifigan.py", line 25, in __init__ h = AttrDict(json.loads(data)) File "/usr/lib/python3.6/json/__init__.py", line 354, in loads return _default_decoder.decode(s) File "/usr/lib/python3.6/json/decoder.py", line 339, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by BenAAndrew** [comment]
Hi, have you added the default vocoder following the steps here: https://benaandrew.github.io/Voice-Cloning-App/synthesis/#add-a-vocoder ?

**Comment by BenAAndrew** [comment]
Closing due to inactivity
