### ISSUE TITLE
"No such name"

### ISSUE THREAD

**Issue by MikeyMK** [BenAAndrew/Voice-Cloning-App#118]
I'm getting an error when trying to start the process of creating a dataset. 
I select my audio file and my text file, but I get an error saying "no such name", looks like it happens when trying to find the "text.txt" file. 

Is there something I'm doing wrong? 

Thanks!

**Comment by BenAAndrew** [comment]
Could you copy the full error log?

**Comment by MikeyMK** [comment]
Loading data from C:\Users\Mike\Desktop\Voice-Cloning\data
Server initialized for threading.
Loading data from C:\Users\Mike\Desktop\Voice-Cloning\data
Server initialized for threading.
INFO:matplotlib.font_manager:generated new fontManager
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Mike\AppData\Local\Temp\_MEI188362\nltk_data.
[nltk_data]     ..
[nltk_data]   Package punkt is already up-to-date!
WARNING:werkzeug:WebSocket transport not available. Install eventlet or gevent and gevent-websocket for improved performance.
 * Serving Flask app "main" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.0.108:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [17/Apr/2022 11:55:30] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [17/Apr/2022 11:55:30] "GET /static/main.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [17/Apr/2022 11:55:30] "GET /static/pane.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [17/Apr/2022 11:55:30] "GET /static/advanced.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [17/Apr/2022 11:55:30] "GET /static/dataset.js HTTP/1.1" 200 -
Starting Thread
INFO:werkzeug:127.0.0.1 - - [17/Apr/2022 11:56:45] "POST / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [17/Apr/2022 11:56:45] "GET /static/main.css HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [17/Apr/2022 11:56:45] "GET /static/application.js HTTP/1.1" 200 -
The WebSocket transport is not available, you must install a WebSocket server that is compatible with your async mode to enable it. See the documentation for details. (further occurrences of this error will be logged with level INFO)
ERROR:engineio.server:The WebSocket transport is not available, you must install a WebSocket server that is compatible with your async mode to enable it. See the documentation for details. (further occurrences of this error will be logged with level INFO)
D0N-LK5BQWQaz2vqAAAA: Sending packet OPEN data {'sid': 'D0N-LK5BQWQaz2vqAAAA', 'upgrades': [], 'pingTimeout': 20000, 'pingInterval': 25000}
INFO:engineio.server:D0N-LK5BQWQaz2vqAAAA: Sending packet OPEN data {'sid': 'D0N-LK5BQWQaz2vqAAAA', 'upgrades': [], 'pingTimeout': 20000, 'pingInterval': 25000}
INFO:werkzeug:127.0.0.1 - - [17/Apr/2022 11:56:45] "GET /socket.io/?EIO=4&transport=polling&t=O0uFQFT HTTP/1.1" 200 -
D0N-LK5BQWQaz2vqAAAA: Received packet MESSAGE data 0/voice,
INFO:engineio.server:D0N-LK5BQWQaz2vqAAAA: Received packet MESSAGE data 0/voice,
D0N-LK5BQWQaz2vqAAAA: Sending packet MESSAGE data 0/voice,{"sid":"oRKyAD_Z3zSOpBSQAAAB"}
INFO:engineio.server:D0N-LK5BQWQaz2vqAAAA: Sending packet MESSAGE data 0/voice,{"sid":"oRKyAD_Z3zSOpBSQAAAB"}
INFO:werkzeug:127.0.0.1 - - [17/Apr/2022 11:56:45] "POST /socket.io/?EIO=4&transport=polling&t=O0uFQKb&sid=D0N-LK5BQWQaz2vqAAAA HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [17/Apr/2022 11:56:46] "GET /socket.io/?EIO=4&transport=polling&t=O0uFQKc&sid=D0N-LK5BQWQaz2vqAAAA HTTP/1.1" 200 -
emitting event "logs" to all [/voice]
INFO:socketio.server:emitting event "logs" to all [/voice]
D0N-LK5BQWQaz2vqAAAA: Sending packet MESSAGE data 2/voice,["logs",{"text":"Converting C:\\Users\\Mike\\Desktop\\Voice-Cloning\\data\\datasets\\Test\\TestDialogue.mp3..."}]
INFO:werkzeug:127.0.0.1 - - [17/Apr/2022 11:56:50] "GET /socket.io/?EIO=4&transport=polling&t=O0uFQPg&sid=D0N-LK5BQWQaz2vqAAAA HTTP/1.1" 200 -
INFO:engineio.server:D0N-LK5BQWQaz2vqAAAA: Sending packet MESSAGE data 2/voice,["logs",{"text":"Converting C:\\Users\\Mike\\Desktop\\Voice-Cloning\\data\\datasets\\Test\\TestDialogue.mp3..."}]
INFO:voice:Converting C:\Users\Mike\Desktop\Voice-Cloning\data\datasets\Test\TestDialogue.mp3...
ffmpeg version N-103408-g831718bbab-20210827 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 10-win32 (GCC) 20210408
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-gpl --enable-version3 --disable-debug --disable-w32threads --enable-pthreads --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libvmaf --enable-vulkan --disable-libxcb --disable-xlib --enable-amf --enable-libaom --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libglslang --enable-libgme --enable-libass --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librav1e --enable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --disable-libdrm --disable-vaapi --enable-libvidstab --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags= --extra-libs=-lgomp --extra-version=20210827
  libavutil      57.  4.101 / 57.  4.101
  libavcodec     59.  6.100 / 59.  6.100
  libavformat    59.  4.102 / 59.  4.102
  libavdevice    59.  0.101 / 59.  0.101
  libavfilter     8.  4.100 /  8.  4.100
  libswscale      6.  0.100 /  6.  0.100
  libswresample   4.  0.100 /  4.  0.100
  libpostproc    56.  0.100 / 56.  0.100
[mp3 @ 00000212a8445540] Estimating duration from bitrate, this may be inaccurate
Input #0, mp3, from 'C:\Users\Mike\Desktop\Voice-Cloning\data\datasets\Test\TestDialogue.mp3':
  Metadata:
    title           : Dialogue
    encoded_by      : Mixcraft 7.7 64-Bit Build 316
    track           : 0/1
    genre           : Rock
    date            : 2021
  Duration: 01:10:55.04, start: 0.000000, bitrate: 320 kb/s
  Stream #0:0: Audio: mp3, 44100 Hz, stereo, fltp, 320 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (mp3 (mp3float) -> pcm_s16le (native))
Press [q] to stop, [?] for help
Output #0, wav, to 'C:\Users\Mike\Desktop\Voice-Cloning\data\datasets\Test\TestDialogue-converted.wav':
  Metadata:
    INAM            : Dialogue
    ITCH            : Mixcraft 7.7 64-Bit Build 316
    IPRT            : 0/1
    IGNR            : Rock
    ICRD            : 2021
    ISFT            : Lavf59.4.102
  Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 22050 Hz, mono, s16, 352 kb/s
    Metadata:
      encoder         : Lavc59.6.100 pcm_s16le
size=  183249kB time=01:10:55.03 bitrate= 352.8kbits/s speed= 474x
video:0kB audio:183249kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000096%
emitting event "logs" to all [/voice]
INFO:socketio.server:emitting event "logs" to all [/voice]
D0N-LK5BQWQaz2vqAAAA: Sending packet MESSAGE data 2/voice,["logs",{"text":"Loading C:\\Users\\Mike\\Desktop\\Voice-Cloning\\data\\datasets\\Test\\text.txt..."}]
INFO:werkzeug:127.0.0.1 - - [17/Apr/2022 11:56:59] "GET /socket.io/?EIO=4&transport=polling&t=O0uFRNz&sid=D0N-LK5BQWQaz2vqAAAA HTTP/1.1" 200 -
INFO:engineio.server:D0N-LK5BQWQaz2vqAAAA: Sending packet MESSAGE data 2/voice,["logs",{"text":"Loading C:\\Users\\Mike\\Desktop\\Voice-Cloning\\data\\datasets\\Test\\text.txt..."}]
INFO:voice:Loading C:\Users\Mike\Desktop\Voice-Cloning\data\datasets\Test\text.txt...
emitting event "error" to all [/voice]
INFO:socketio.server:emitting event "error" to all [/voice]
D0N-LK5BQWQaz2vqAAAA: Sending packet MESSAGE data 2/voice,["error",{"type":"ValueError","text":"no such name","stacktrace":"Traceback (most recent call last):\n  File \"application\\utils.py\", line 62, in background_task\n  File \"dataset\\create_dataset.py\", line 89, in create_dataset\n  File \"dataset\\create_dataset.py\", line 85, in create_dataset\n  File \"dataset\\clip_generator.py\", line 340, in clip_generator\n  File \"dataset\\clip_generator.py\", line 340, in <listcomp>\nValueError: no such name\n"}]
INFO:werkzeug:127.0.0.1 - - [17/Apr/2022 11:56:59] "GET /socket.io/?EIO=4&transport=polling&t=O0uFTbs&sid=D0N-LK5BQWQaz2vqAAAA HTTP/1.1" 200 -
INFO:engineio.server:D0N-LK5BQWQaz2vqAAAA: Sending packet MESSAGE data 2/voice,["error",{"type":"ValueError","text":"no such name","stacktrace":"Traceback (most recent call last):\n  File \"application\\utils.py\", line 62, in background_task\n  File \"dataset\\create_dataset.py\", line 89, in create_dataset\n  File \"dataset\\create_dataset.py\", line 85, in create_dataset\n  File \"dataset\\clip_generator.py\", line 340, in clip_generator\n  File \"dataset\\clip_generator.py\", line 340, in <listcomp>\nValueError: no such name\n"}]
Exception in thread Thread-9:
Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "threading.py", line 864, in run
  File "application\utils.py", line 66, in background_task
  File "application\utils.py", line 62, in background_task
  File "dataset\create_dataset.py", line 89, in create_dataset
  File "dataset\create_dataset.py", line 85, in create_dataset
  File "dataset\clip_generator.py", line 340, in clip_generator
  File "dataset\clip_generator.py", line 340, in <listcomp>
ValueError: no such name

**Comment by MikeyMK** [comment]
I do have eventlet, gevent, and gevent-websocket installed but it still tells gives me the websocket error as well, not sure if it is related to the "no such name" issue. 
Running on Windows 10.

**Comment by BenAAndrew** [comment]
Hmm, that error is quite vague and it's not obvious from the logs why it failed. A few more questions:
- Are you using English as your language? 
- Does your source text only contain standard English characters?
- Are you using a subtitle file or plain text file?

**Comment by MikeyMK** [comment]
Yup, English is the language and only contains standard characters and punctuation. 
I'm using a plain .txt file. Since the audio was split from many episodes of a show, I had to type out the majority of the text myself. Each line of text is on a separate line, not sure if that makes a difference? 

I've also noticed that a copy of the txt file and audio file is created in the /datasets/Test folder, but is automatically deleted when the error occurs.

**Comment by BenAAndrew** [comment]
That all sounds fine then. You can send me a link to your data if you like (by Discord DM or email) and I might be able to do further investigation

**Comment by RayDAnt3D** [comment]
Just wanted to chime in that I too ran into this issue just recently, and was able to trace it back to the presence of tab and/or multiple-space indents at the beginnings of lines in a UTF-8 formatted text file.

**Comment by rikabi89** [comment]
fyi for anyone having this issue. https://www.browserling.com/tools/remove-whitespace - remove all tab/space easily and it fixed the issues for me without me manually doing myself.
