### ISSUE TITLE
bug when running main.py

### ISSUE THREAD

**Issue by king-dahmanus** [BenAAndrew/Voice-Cloning-App#129]
so, after I installed visual studio build tools, I decided to get back into this, I installed all the dependencies,  and tried running python3 main.py, so I got this error:
Traceback (most recent call last):
  File "c:\Users\ilyes\Desktop\repos\voice-cloning-app\main.py", line 6, in <module>
    from flask_socketio import SocketIO
  File "D:\python3\envs\vca\lib\site-packages\flask_socketio\__init__.py", line 18, in <module>
    import flask
  File "D:\python3\envs\vca\lib\site-packages\flask\__init__.py", line 14, in <module>
    from jinja2 import escape
ImportError: cannot import name 'escape' from 'jinja2' (D:\python3\envs\vca\lib\site-packages\jinja2\__init__.py)

(
I tried purging the pip wheel caches and reinstalling both jinjaa2 and markupsafe(its dependency) but the error persists. Can you help me fix it? Thanks

**Comment by BenAAndrew** [comment]
Hi @king-dahmanus, are you running a manual install? If so, check the following:
1. You are using the correct version of python (3.6)
2. You installed with `pip install -r requirements.txt` 
3. You have the correct version of Flask (1.1.2) (check with `pip list`)
