### ISSUE TITLE
dll import failed

### ISSUE THREAD

**Issue by king-dahmanus** [BenAAndrew/Voice-Cloning-App#139]
ok, so I'm using anaconda on windows. I made a venv that has python3.6 since that's what vca uses. I activate it and run the instalation of dependancies, then according to a user on discord, I reinstalled another version of numba and another package which are different from the latest, Below I'll give my pip freeze output.
And now I made some progress(with an error of course). When I run python main.py, I get this:
Loading data from data
Server initialized for threading.
Loading data from C:\Users\ilyes\Desktop\repos\voice-cloning-app\data
Server initialized for threading.
Traceback (most recent call last):
  File "main.py", line 52, in <module>
    from application.views import *  # noqa
  File "C:\Users\ilyes\Desktop\repos\voice-cloning-app\application\views.py", line 20, in <module>
    from dataset.create_dataset import create_dataset
  File "C:\Users\ilyes\Desktop\repos\voice-cloning-app\dataset\create_dataset.py", line 16, in <module>
    from dataset.transcribe import Silero
  File "C:\Users\ilyes\Desktop\repos\voice-cloning-app\dataset\transcribe.py", line 8, in <module>
    import deepspeech
  File "d:\anaconda3\envs\vca\lib\site-packages\deepspeech\__init__.py", line 23, in <module>
    from deepspeech.impl import Version as version
  File "d:\anaconda3\envs\vca\lib\site-packages\deepspeech\impl.py", line 13, in <module>
    from . import _impl
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

(
my pip packages:
altgraph==0.17.2
audioread==2.1.9
bidict==0.21.4
certifi==2021.5.30
cffi==1.15.1
chardet==4.0.0
click==8.0.4
colorama==0.4.5
cycler==0.11.0
dataclasses==0.8
decorator==5.1.1
deepspeech==0.9.3
Flask==1.1.2
Flask-SocketIO==5.0.1
future==0.18.2
idna==2.10
importlib-metadata==4.8.3
importlib-resources==5.4.0
inflect==0.2.5
itsdangerous==2.0.1
Jinja2==3.0.3
joblib==1.1.0
kiwisolver==1.3.1
librosa==0.6.0
llvmlite==0.32.1
MarkupSafe==2.0.1
matplotlib==3.2.2
nltk==3.6.2
numba==0.45.0
numpy==1.14.4
omegaconf==2.0.6
pefile==2022.5.30
Pillow==8.4.0
pycparser==2.21
pydub==0.24.1
pyinstaller==4.10
pyinstaller-hooks-contrib==2022.0
pyparsing==3.0.9
pysrt==1.1.2
python-dateutil==2.8.2
python-engineio==4.3.3
python-socketio==5.7.0
pywin32-ctypes==0.2.0
PyYAML==6.0
regex==2022.7.9
requests==2.25.1
resampy==0.2.2
scikit-learn==0.24.2
scipy==1.4.1
six==1.16.0
SoundFile==0.10.3.post1
threadpoolctl==3.1.0
torch==1.9.0+cpu
torchaudio==0.9.0
torchvision==0.10.0+cpu
tqdm==4.64.0
typing_extensions==4.1.1
Unidecode==1.0.22
urllib3==1.26.10
webrtcvad==2.0.10
Werkzeug==2.0.3
wincertstore==0.2
zipp==3.6.0
hope I will get some help here. Thanks

**Comment by king-dahmanus** [comment]
I believe that is the error I first got when running the prebuilt cpu only executable

**Comment by king-dahmanus** [comment]
does anybody know what I should do about this dll file?

**Comment by BenAAndrew** [comment]
Hi @king-dahmanus,

This is quite an annoying problem I also had for a while with deepspeech.
It's build is quite flaky so I've only made it work with Python 3.6.

Please try creating a fresh Python 3.6 virtual environment and run `pip install -r requirements.txt`. Hopefully it will fix your issue as I'm not sure how else to tackle this issue.

**Comment by king-dahmanus** [comment]
that's the thing, I used a special venv that uses python3.6 specifically. When I ran main.py the first time it produced some error. On discord, they suggested to me that I should install a different version of numpy and llvmlight or something I forgot the exact packages. But I tried that and it worked, because I ran into the same error that occured to me when I used the executable

**Comment by BenAAndrew** [comment]
What was the original error you had when running `main.py`?

**Comment by king-dahmanus** [comment]
it's  
python main.py
Loading data from data
Server initialized for threading.
Loading data from C:\Users\ilyes\Desktop\repos\voice-cloning-app\data
Server initialized for threading.
Traceback (most recent call last):
  File "main.py", line 52, in <module>
    from application.views import *  # noqa
  File "C:\Users\ilyes\Desktop\repos\voice-cloning-app\application\views.py", line 11, in <module>
    from application.utils import (
  File "C:\Users\ilyes\Desktop\repos\voice-cloning-app\application\utils.py", line 8, in <module>
    import librosa
  File "d:\anaconda3\envs\vca\lib\site-packages\librosa\__init__.py", line 12, in <module>
    from . import core
  File "d:\anaconda3\envs\vca\lib\site-packages\librosa\core\__init__.py", line 102, in <module>
    from .time_frequency import *  # pylint: disable=wildcard-import
  File "d:\anaconda3\envs\vca\lib\site-packages\librosa\core\time_frequency.py", line 10, in <module>
    from ..util.exceptions import ParameterError
  File "d:\anaconda3\envs\vca\lib\site-packages\librosa\util\__init__.py", line 70, in <module>
    from . import decorators
  File "d:\anaconda3\envs\vca\lib\site-packages\librosa\util\decorators.py", line 9, in <module>
    from numba.decorators import jit as optional_jit
  File "d:\anaconda3\envs\vca\lib\site-packages\numba\__init__.py", line 196, in <module>
    import numba.typed
  File "d:\anaconda3\envs\vca\lib\site-packages\numba\typed\__init__.py", line 3, in <module>
    from .typeddict import Dict
  File "d:\anaconda3\envs\vca\lib\site-packages\numba\typed\typeddict.py", line 19, in <module>
    @njit
  File "d:\anaconda3\envs\vca\lib\site-packages\numba\decorators.py", line 238, in njit
    return jit(*args, **kws)
  File "d:\anaconda3\envs\vca\lib\site-packages\numba\decorators.py", line 175, in jit
    return wrapper(pyfunc)
  File "d:\anaconda3\envs\vca\lib\site-packages\numba\decorators.py", line 191, in wrapper
    **dispatcher_args)
  File "d:\anaconda3\envs\vca\lib\site-packages\numba\dispatcher.py", line 650, in __init__
    self.targetctx = self.targetdescr.target_context
  File "d:\anaconda3\envs\vca\lib\site-packages\numba\targets\registry.py", line 50, in target_context
    return self._toplevel_target_context
  File "d:\anaconda3\envs\vca\lib\site-packages\numba\utils.py", line 390, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "d:\anaconda3\envs\vca\lib\site-packages\numba\targets\registry.py", line 34, in _toplevel_target_context
    return cpu.CPUContext(self.typing_context)
  File "d:\anaconda3\envs\vca\lib\site-packages\numba\targets\base.py", line 260, in __init__
    self.init()
  File "d:\anaconda3\envs\vca\lib\site-packages\numba\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "d:\anaconda3\envs\vca\lib\site-packages\numba\targets\cpu.py", line 51, in init
    self._internal_codegen = codegen.JITCPUCodegen("numba.exec")
  File "d:\anaconda3\envs\vca\lib\site-packages\numba\targets\codegen.py", line 628, in __init__
    self._init(self._llvm_module)
  File "d:\anaconda3\envs\vca\lib\site-packages\numba\targets\codegen.py", line 637, in _init
    tm = target.create_target_machine(**tm_options)
TypeError: create_target_machine() got an unexpected k
then according to someone on discord I did the following:
pip install llvmlite==0.32.1
and
pip install numba==0.45.0
which led to the first post error
