### ISSUE TITLE
Error Build dataset

### ISSUE THREAD

**Issue by raul-parada** [BenAAndrew/Voice-Cloning-App#142]
I'm using the Windows version  "Voice-Cloning-App-1.1.1-cpuonly" on Windows 10.

I've uploaded a text (26kb) and its audio in mp3 (76MB). I've chosen the Spanish language (since it is the language of these files. I've configured confidence to 0.95 and length from 1920 to 1980 and when I click on Submit and I get this error.

![image](https://user-images.githubusercontent.com/8438920/181752618-87a538b3-0cba-4ea2-ad87-10634a031786.png)

**Comment by Avedena** [comment]
Same here with German:
```python
Type: FileNotFoundError
Text: [Errno 2] No such file or directory: 'alphabets\\German.txt'
Full: Traceback (most recent call last): File "flask\app.py", line 1950, in full_dispatch_request File "flask\app.py", line 1936, in dispatch_request File "application\views.py", line 121, in create_dataset_post File "application\views.py", line 87, in get_symbols File "training\utils.py", line 189, in load_symbols FileNotFoundError: [Errno 2] No such file or directory: 'alphabets\\German.txt'
```
Before starting dataset creation I add a new language. I also can find the files under the data folder.

**Comment by Avedena** [comment]
It looks like there is an issue with the Windows binary file.
Clone the repository and install it manually.
This solves it for me on the master branch.
Or create a new Language and name it ES for example and upload a language model.
