### ISSUE TITLE
App is not starting.

### ISSUE THREAD

**Issue by LibirSoft** [BenAAndrew/Voice-Cloning-App#148]
I installed all requirements with python 3.6.15. When i try to start app i am getting this error 
```Server initialized for threading.
Traceback (most recent call last):
  File "main.py", line 52, in <module>
    from application.views import *  # noqa
  File "/home/libir/Desktop/voiceCloning/Voice-Cloning-App/application/views.py", line 11, in <module>
    from application.utils import (
  File "/home/libir/Desktop/voiceCloning/Voice-Cloning-App/application/utils.py", line 8, in <module>
    import librosa
  File "/home/libir/.pyenv/versions/3.6.15/lib/python3.6/site-packages/librosa/__init__.py", line 12, in <module>
    from . import core
  File "/home/libir/.pyenv/versions/3.6.15/lib/python3.6/site-packages/librosa/core/__init__.py", line 103, in <module>
    from .audio import *  # pylint: disable=wildcard-import
  File "/home/libir/.pyenv/versions/3.6.15/lib/python3.6/site-packages/librosa/core/audio.py", line 12, in <module>
    import resampy
  File "/home/libir/.pyenv/versions/3.6.15/lib/python3.6/site-packages/resampy/__init__.py", line 7, in <module>
    from .core import *
  File "/home/libir/.pyenv/versions/3.6.15/lib/python3.6/site-packages/resampy/core.py", line 9, in <module>
    from .interpn import resample_f_s, resample_f_p
  File "/home/libir/.pyenv/versions/3.6.15/lib/python3.6/site-packages/resampy/interpn.py", line 75, in <module>
    nopython=True,
TypeError: guvectorize() missing 1 required positional argument: 'signature'
```
Also i am using EndeavourOS.

**Comment by CrocodileCroco** [comment]
Solution : 

First, upgrade pip

Next you will these 2 commands : 
`pip install resampy==0.3.0`
`pip install numba==0.48`

That worked for me

**Comment by acdop100** [comment]
> Solution :
> 
> First, upgrade pip
> 
> Next you will these 2 commands : `pip install resampy==0.3.0` `pip install numba==0.48`
> 
> That worked for me

Worked for me on windows too. Thanks!
