### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by skydam** [BenAAndrew/Voice-Cloning-App#150]
When I go to synthesize and submit, this is the error message that appears: Text: Expecting value: line 1 column 1 (char 0)
Full: Traceback (most recent call last): File "flask\app.py", line 1950, in full_dispatch_request File "flask\app.py", line 1936, in dispatch_request File "application\views.py", line 302, in synthesis_setup_post File "synthesis\vocoders\hifigan.py", line 25, in __init__ File "json\__init__.py", line 354, in loads File "json\decoder.py", line 339, in decode File "json\decoder.py", line 357, in raw_decode json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by steveisd** [comment]
I got a similar error and it was because forgot to upload config.json file with vocoder model I was using (there are two upload buttons, the other is for the config.json)
In my case I just downloaded the config.json with the hifigan model from the 'g_' model link

Hope this helps, and for anyone else too
