### ISSUE TITLE
cannot export dataset

### ISSUE THREAD

**Issue by ariyach** [BenAAndrew/Voice-Cloning-App#153]
when i'm trying to export the dataset
got this error

**Type**: TypeError
**Text**: send_file() got an unexpected keyword argument 'attachment_filename'
**Full**: Traceback (most recent call last): File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request rv = self.dispatch_request() File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1796, in dispatch_request return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args) File "C:\Users\user\voice-cloning-app\application\views.py", line 533, in download_dataset return send_file( TypeError: send_file() got an

**Comment by ariyach** [comment]
nvm, it works after reinstalling
