### ISSUE TITLE
Loading error

### ISSUE THREAD

**Issue by andytyrer** [BenAAndrew/Voice-Cloning-App#155]
Hi

I am on Python 3.62 and getting the follow error when running main.py

Traceback (most recent call last):
  File "main.py", line 6, in <module>
    from flask_socketio import SocketIO
  File "C:\Users\andyr\desktop\Voice-Cloning-App\lib\site-packages\flask_socketio\__init__.py", line 18, in <module>
    import flask
  File "C:\Users\andyr\desktop\Voice-Cloning-App\lib\site-packages\flask\__init__.py", line 16, in <module>
    from werkzeug.exceptions import abort
  File "C:\Users\andyr\desktop\Voice-Cloning-App\lib\site-packages\werkzeug\__init__.py", line 2, in <module>
    from .test import Client as Client
  File "C:\Users\andyr\desktop\Voice-Cloning-App\lib\site-packages\werkzeug\test.py", line 30, in <module>
    from .sansio.multipart import Data
  File "C:\Users\andyr\desktop\Voice-Cloning-App\lib\site-packages\werkzeug\sansio\multipart.py", line 2, in <module>
    from dataclasses import dataclass
  File "C:\Users\andyr\desktop\Voice-Cloning-App\lib\dataclasses.py", line 998
    def dataclass(cls=None, /, *, init=True, repr=True, eq=True, order=False,
    
    Any ideas

**Comment by gnmarten** [comment]
same problem here
related to flask-socket.io "Sending packet PING data None"
environment: Ubuntu 20.4, manual install via git clone (and pip requirements) in a conda environment), solved the numba/scipy issue

the exe installer version works in Windows, but I want to use it with the default German model
