### ISSUE TITLE
Cannot use German for my dataset

### ISSUE THREAD

**Issue by luigi052005** [BenAAndrew/Voice-Cloning-App#169]
Type: FileNotFoundError
Text: [Errno 2] No such file or directory: 'alphabets\\German.txt'
Full: Traceback (most recent call last): File "flask\app.py", line 1950, in full_dispatch_request File "flask\app.py", line 1936, in dispatch_request File "application\views.py", line 121, in create_dataset_post File "application\views.py", line 87, in get_symbols File "training\utils.py", line 172, in load_symbols FileNotFoundError: [Errno 2] No such file or directory: 'alphabets\\German.txt'

**Comment by SandUhrGucker** [comment]
if the file exists, ensure the encoding is utf8. This fixes the error for me
