### ISSUE TITLE
i dont know   ;)

### ISSUE THREAD

**Issue by kalle07** [BenAAndrew/Voice-Cloning-App#183]
Type: NotADirectoryError
Text: [WinError 267] Der Verzeichnisname ist ungültig: 'd:\\voicecloningAPP\\data\\models\\tacotron2_statedict.pt'
Full: Traceback (most recent call last): File "C:\ProgramData\anaconda3\envs\voicecloningAPP\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request rv = self.dispatch_request() File "C:\ProgramData\anaconda3\envs\voicecloningAPP\lib\site-packages\flask\app.py", line 1936, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args) File "d:\voicecloningAPP\application\views.py", line 210, in get_train checkpoints=get_checkpoints(), File "d:\voicecloningAPP\application\views.py", line 78, in get_checkpoints for model in os.listdir(paths["models"]) File "d:\voicecloningAPP\application\views.py", line 79, in <dictcomp> if os.listdir(os.path.join(paths["models"], model)) NotADirectoryError: [WinError 267] Der Verzeichnisname ist ungültig: 'd:\\voicecloningAPP\\data\\models\\tacotron2_statedict.pt'

**Comment by SandUhrGucker** [comment]
ensure the given config points to a directory, not a file. 
also remove blanks in file+directorynames if you installed so.

**Comment by bitplane** [comment]
Having a bit of a bug tracker clean-up, and will close this in favour of #189
