### ISSUE TITLE
BadRequestKeyError (Trying to synthesize)

### ISSUE THREAD

**Issue by Maichelanger** [BenAAndrew/Voice-Cloning-App#59]
_Type: BadRequestKeyError
Text: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Full: Traceback (most recent call last): File "flask\app.py", line 1950, in full_dispatch_request File "flask\app.py", line 1936, in dispatch_request File "application\views.py", line 262, in synthesis_setup_post File "werkzeug\datastructures.py", line 377, in __getitem__ werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand._

This error shows whenever I click "Submit" on the "Synthesis" stage.
I think it may be related to the fact that, at the end of the page, there's a blank menu with no options to choose from.

**Comment by Maichelanger** [comment]
Nevermind.
I didn't know you had to upload the models yourself.
