### ISSUE TITLE
reached max decoder steps no matter what

### ISSUE THREAD

**Issue by FlashlightET** [BenAAndrew/Voice-Cloning-App#68]
Type: Exception
Text: Warning! Reached max decoder steps. Either the model is low quality or the given sentence is too short/long
Full: Traceback (most recent call last): File "flask\app.py", line 1950, in full_dispatch_request File "flask\app.py", line 1936, in dispatch_request File "application\views.py", line 324, in synthesis_post File "synthesis\synthesize.py", line 195, in synthesize File "training\tacotron2_model\model.py", line 604, in inference File "training\tacotron2_model\model.py", line 493, in inference Exception: Warning! Reached max decoder steps. Either the model is low quality or the given sentence is too short/long

ive even tried changing the html to change the max value on the sliders. did i just waste time? the model was pretrained and 18000 iters, it shouldn't be failing on a sentence as simple as "yo mama"

**Comment by FlashlightET** [comment]
maybe my model just sucks
