### ISSUE TITLE
New language error 

### ISSUE THREAD

**Issue by dDoom** [BenAAndrew/Voice-Cloning-App#80]
I loaded the dictionary and dataset for the Russian language, everything went correctly. It determines the total time, but at the start of training crashed. Help, what can it be?

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/Voice-Cloning-App/application/utils.py", line 66, in background_task
    raise e
  File "/home/ubuntu/Voice-Cloning-App/application/utils.py", line 62, in background_task
    func(logging=logger, **kwargs)
  File "/home/ubuntu/Voice-Cloning-App/training/train.py", line 186, in train
    for _, batch in enumerate(train_loader):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ubuntu/Voice-Cloning-App/training/voice_dataset.py", line 127, in __getitem__
    return self.get_mel_text_pair(self.filepaths_and_text[index])
  File "/home/ubuntu/Voice-Cloning-App/training/voice_dataset.py", line 68, in get_mel_text_pair
    text = self.get_text(text)
  File "/home/ubuntu/Voice-Cloning-App/training/voice_dataset.py", line 122, in get_text
    sequence = [self.symbol_to_id[s] for s in text if s != "_"]
  File "/home/ubuntu/Voice-Cloning-App/training/voice_dataset.py", line 122, in <listcomp>
    sequence = [self.symbol_to_id[s] for s in text if s != "_"]
KeyError: 's'
```

**Comment by BenAAndrew** [comment]
I've improved the error messages with 1.0.3 so you should see a new message like "Invalid characters (for alphabet): ..." which will list what invalid characters you have in your dataset
